### ISSUE TITLE
Select new fonts for this year

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2020.code4lib.org#11]
Since we've used the same fonts for the last few years, it would be nice to try out some new ones. I'll post some screenshots and get feedback from the group.

**Comment by kaitlinnewson** [comment]
Throwing out some ideas in the following comments. We can also swap some of these around.

**Comment by kaitlinnewson** [comment]
Serif: Playfair Display SC
Sans serif: Nunito

![talk-description](https://user-images.githubusercontent.com/6903515/64040180-7005bd00-cb2a-11e9-8b52-78c3d0202d6b.png)
![schedule](https://user-images.githubusercontent.com/6903515/64040181-7005bd00-cb2a-11e9-8403-bf03e5d425ce.png)
![conduct](https://user-images.githubusercontent.com/6903515/64040182-7005bd00-cb2a-11e9-9a34-c69c96d56c5d.png)
![home](https://user-images.githubusercontent.com/6903515/64040183-7005bd00-cb2a-11e9-8b02-a38349ccb405.png)

**Comment by kaitlinnewson** [comment]
Serif: Arvo
Sans serif: Cabin
![talk-description](https://user-images.githubusercontent.com/6903515/64040243-9cb9d480-cb2a-11e9-84c3-2c410f9c7e30.png)
![schedule](https://user-images.githubusercontent.com/6903515/64040244-9cb9d480-cb2a-11e9-8733-21666f8ebed9.png)
![conduct](https://user-images.githubusercontent.com/6903515/64040245-9cb9d480-cb2a-11e9-9eb6-d6675bf9e63f.png)
![home](https://user-images.githubusercontent.com/6903515/64040246-9cb9d480-cb2a-11e9-8153-2c52374f1147.png)

**Comment by kaitlinnewson** [comment]
Serif: PT Serif
Sans serif: PT Sans

![talk-description](https://user-images.githubusercontent.com/6903515/64040296-b824df80-cb2a-11e9-9df1-650b1a032f7e.png)
![schedule](https://user-images.githubusercontent.com/6903515/64040297-b824df80-cb2a-11e9-8b6b-4f32638df760.png)
![conduct](https://user-images.githubusercontent.com/6903515/64040298-b824df80-cb2a-11e9-8c8a-461590a47c3d.png)
![home](https://user-images.githubusercontent.com/6903515/64040299-b824df80-cb2a-11e9-861c-aa650ff0e773.png)

**Comment by kaitlinnewson** [comment]
Serif: Cormorant SC
Sans serif: Open Sans
![talk-description](https://user-images.githubusercontent.com/6903515/64040355-d8ed3500-cb2a-11e9-969a-1aa8138bcd22.png)
![schedule](https://user-images.githubusercontent.com/6903515/64040356-d8ed3500-cb2a-11e9-9d4d-fa632ce853d0.png)
![conduct](https://user-images.githubusercontent.com/6903515/64040357-d8ed3500-cb2a-11e9-9f2c-63851abeb8bb.png)
![home](https://user-images.githubusercontent.com/6903515/64040358-d8ed3500-cb2a-11e9-9862-771cc467f9b8.png)

**Comment by phette23** [comment]
I think I like the PT pair the best and maybe Arvo/Cabin second, but they're all pretty close and I'm not too opinionated.

**Comment by kellyhiser** [comment]
I also like PT and Arvo.

**Comment by dzoladz** [comment]
Adding another +1 for PT and Arvo. I don't have a strong preference for one over the other, but PT makes me think of Pittsburgh... so if pressed, I'd lean towards PT.
