### ISSUE TITLE
Additional features for the newcomer dinner list

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#113]
See #110 and #112 for some context. The table of restaurant options is functional right now but I was thinking of these additional features:

- exposing the description information (maybe some kind of question mark/info icon that shows a tooltip on hover?)
- letting the table be sorted/filtered e.g. [jQuery datatables](https://datatables.net/)

**Comment by ranti** [comment]
Exposing the description sounds useful. It is my understanding tooltip might not work well with screen reader if it's not coded properly. 
See https://stackoverflow.com/q/54333902 for coding possibility.

**Comment by dzoladz** [comment]
I was playing around with exposing the description via tooltips. I'm able to have VoiceOver read the venue description in a tooltip.

Since I'm updating the data, I can work on adding the description as well.

**Comment by ranti** [comment]
- Code looks OK to me, but the table still is not sortable on the github hosted site. 
- I just noticed we have two "Nicky's Thai Kitchen" on the list with different distance details. Not sure if they are indeed two locations.  Their website doesn't seem to work.

**Comment by dzoladz** [comment]
Per @kaitlinnewson, loading dataTables over HTTPS appears to have resolved the issue on the GitHub hosted site.

**Comment by dzoladz** [comment]
@phette23 I've removed myself from this issue. Are you able to close it?
