### ISSUE TITLE
Social Activities Information for Website

### ISSUE THREAD

**Issue by yo-bj** [code4lib/2020.code4lib.org#115]
Hello folks,

The Social Activities Committee are currently wrapping up work on the following items:

- Newcomer Dinner signup document
- Google Map with conference locations, activities, and food/drink locations
- DIY Events signup document
- Game Night signups

Beyond the Newcomer Dinner signup document, the rest of the documents are not on a hard schedule for publication. I'm assuming that a week's lead time would be enough for posting the links or info to the website, but I want to check in to confirm that lead time assumption.

**Comment by phette23** [comment]
I think a week is OK. We are scheduled to have a meeting next week so we can get someone assigned to this issue who is prepared for that turnaround.

**Comment by yo-bj** [comment]
We have some documents ready to publish. Please publish the following links/information on 2/10/2020:

- https://docs.google.com/document/d/1XCql9YgWydMluKfeAN9veDfms8u38shzE2wLlym179I/edit?usp=sharing

- https://docs.google.com/document/d/1vOgMNG0kOaPdsvnjNLld5xlK7pLKZPYzytp7u14MRnQ/edit?usp=sharing

The Google Map should be ready for immediate posting - https://drive.google.com/open?id=1RI4SjmFkzoYX1k5cUgTlJ5zzjHQeAhui&usp=sharing

We are still waiting on information about DIY Events, Game Night, and Karaoke Night (same night as Game Night). I will get you that information as soon as I receive confirmation on logistics.

**Comment by ranti** [comment]
- [ ] google map activity

- [ ] newcomer dinner information

- [ ] newcomer dinner tranportation

- [ ] game night info

- [ ] karaoke night info
