### ISSUE TITLE
Note about Daylight Savings Time

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#120]
DST is on Sunday (preconference day) so that has the potential to throw some people off. Ann Marie suggested putting a notice somewhere on the website. This was my initial idea:

![dst notice](https://user-images.githubusercontent.com/1024833/72548731-218c5d00-3844-11ea-8edf-4a8e394c6149.png)

**Comment by dzoladz** [comment]
PR #122 merged.
