### ISSUE TITLE
Create page to list lightning talk presenters

### ISSUE THREAD

**Issue by ranti** [code4lib/2020.code4lib.org#188]
So they can get acknowledgement too. Or, if there's a c4l wiki page somewhere, we can link to it instead.  

Monday Lightning Talks 4:10 - 5:10 
- Daniel Sanford, Expectations and Conventions:  A C4L Elevator Story
- Ruth Tillman,  Wikidata & Archives
- Cary Gordon,  Islandora 8/Isle
- Kevin Kochanski, What’s New, Hyku?
- Gretchen Gueguen, Just Scan it All
- Dre Talks About a Thing (slides on podium computer)
- Jeff Gerhard A New (Apple) Skin
- Eric morgan distant reader
- Emily Wahl (british book illustration)

Tuesday Lightning Talks 10:25-11:25 
- Brian Hole, Advancing Hyku - GoogleSlide
- Peter Murray, FOLIO/ReShare
- https://docs.google.com/presentation/d/1nWwkt6wXZSr_-MChaPUmE8KvXgpvzWQlSxXn_jyNYSM/edit
- Viktor, Arweave - PDF
- Bill Dueber, Anchored Search in Solr - PPT
- TJ, Library VPN - PPT
- Andrew Kierig & Sara Nguyen, Bingo4Lib - PPT
- Patrick Murray-John, DH Shop+Pedagogy
- Aiden Sawyer, Libraries & the Researcher Workflow [http://tiny.cc/c4l20-researchworkflow]
- Joshua Lynch, Digital Library Web Development w/imperfect metadata
- Cal Murgu, Fabric

Wednesday Lightning Talks 10:15AM to 11:00AM
 (forthcoming)

**Comment by kaitlinnewson** [comment]
In the past we did a wiki page, e.g.: https://wiki.code4lib.org/Code4Lib2019_Lightning_Talks

I can get this started.

**Comment by kaitlinnewson** [comment]
Page has been started and is available here: https://wiki.code4lib.org/Code4Lib2020_Lightning_Talks
