### ISSUE TITLE
hero image

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#2]
Needs to be CC-licensed or something we have permission to use. Flickr has been very useful in the past.

Dimensions displayed are roughly 1440x370 on a laptop but larger is fine, of course. The main thing is the image has to be very landscape-oriented like that.

What are the most notable Pittsburgh landmarks?

**Comment by phette23** [comment]
https://code4lib2020.library.cmu.edu/attractions

**Comment by kellyhiser** [comment]
last year's hero image dimensions = 3840 × 1670

**Comment by kellyhiser** [comment]
one possibility: 
<img width="1261" alt="Screen Shot 2019-08-01 at 8 34 48 PM" src="https://user-images.githubusercontent.com/8515447/62335921-df40b080-b49b-11e9-80f7-2fafc868d1ae.png">

**Comment by kellyhiser** [comment]
pierogi image source (for idol image): https://www.flickr.com/photos/85567416@N03/37323479330/in/photolist-YS9A5j-d6e4Zm-9qVhPZ-uTdno7-gvR55K-7gfM6a-4GgzG4-5jtcrQ-fzcf1H-88jaCE-TifZMZ-gvQAsn-6mCDpH-d6bkW5-7jcGpB-2eHmYPG-d6bk9q-25qhDt-aic1GV-fh6vH6-pQuspt-5pdinD-6gmcDb-a8UmNv-gvQh6U-gvRbyM-9qVi1k-gvRfqW-6K9kcD-gvRqsv-gvQS6K-gvPCx6-49gfN3-gvRe63-6fvjTt-gvSmfi-4UkFLk-58fAkF-gvNYV2-49gfRj-d6dwmL-74aEe4-6gmcM7-gvR843-5iqi4N-aibZjv-aibcn4-gvP8Bb-gvRw63-8qwoPS

**Comment by ranti** [comment]
I always like nightime city view, but I'm taken with the option 2.

**Comment by tomkeays** [comment]
I like the daytime view as well. It is also less like the [PGH Lab](https://pittsburghpa.gov/innovation-performance/pghlab/index.html) example that Kelly posted in Slack.

**Comment by kaitlinnewson** [comment]
+1 for the daytime photo!

**Comment by phette23** [comment]
I love both these but prefer the nighttime one as I, also, am a sucker for cities at night. Sounds like daytime is the consensus winner, though. @kellyhiser do you feel comfortable adding this to the site? If you want a walkthrough we can Zoom for a bit to do it together. I think all the steps are:

- add the image file
- remove the old one
- update the URL in _includes/homepage/jumbotron
- edit the alt text in _data/conf.yml
- edit attributions.html

**Comment by kellyhiser** [comment]
yup, was planning on it - thanks for this list, @phette23! i'm hoping to grab a spare chunk of time later this afternoon. i'll reach out if i have any trouble, but seems straightforward enough.

**Comment by kellyhiser** [comment]
submitted PR #7
