### ISSUE TITLE
First Timers page edits

### ISSUE THREAD

**Issue by ranti** [code4lib/2020.code4lib.org#24]
Per @jltcummings:

Edit to "Food" section on https://2020.code4lib.org/general-info/first-timers:  The venue will provide lunch Monday and Tuesday, as well as morning and afternoon break snacks Monday through Wednesday morning. Menus will be posted on the website about a month before the conference. There will be caffeine.

**Comment by dzoladz** [comment]
@ranti @phette23 I can review `/first-timers` for generalizations next week, if that works for the both of you.

**Comment by phette23** [comment]
That works for me! I think this page is mostly used closer to the conference itself so I don't feel bad about letting it sit for a week.

**Comment by dzoladz** [comment]
I've made a few minor tweaks to pull in values from `conf.yml` and removed specific references to conference days from the __Food__ section.
