### ISSUE TITLE
colors/theming

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#3]
Select a new theme. We went with the San José Sharks color scheme last year. Not that we need to always do sports team colors, but Pittsburgh has two yellow&black teams (Pirates, Steelers) and those colors have a nice contrast that might work.

**Comment by kaitlinnewson** [comment]
For reference:

- Penguins colors: https://teamcolorcodes.com/pittsburgh-penguins-color-codes/
- Steelers colors: https://teamcolorcodes.com/pittsburgh-steelers-color-codes/
- Pirates colors: https://teamcolorcodes.com/pittsburgh-pirates-color-codes/

I'll start testing these out and see how they look!

**Comment by phette23** [comment]
Ha I forgot there was a _third_ black/yellow team in Pittsburgh. They really love that color pairing.

**Comment by kaitlinnewson** [comment]
@phette23 TIL: Apparently they're a tribute to the Pittsburgh flag https://en.wikipedia.org/wiki/Flag_of_Pittsburgh

**Comment by phette23** [comment]
Once we've selected colors we need to notify Kathy Azevedo <kathy@concentra-cms.com>.

**Comment by kaitlinnewson** [comment]
I'm planning on using the Pirates colors, but have some accessibility work to do before I can get the PR up.

https://teamcolorcodes.com/pittsburgh-pirates-color-codes/

**Comment by phette23** [comment]
@kaitlinnewson sounds good, let me know if there's anything I can do to help.

**Comment by phette23** [comment]
Updated your comment above with some additions/check offs. In general the `p a:-webkit-any-link` style right at the bottom of main.scss is a problem and anywhere it applies (e.g. any text not in a `.general-info` section) doesn't have sufficient contrast.

**Comment by phette23** [comment]
Oh I forgot to mention the diversity scholars also have some weird coloring on hover:

![hodor](https://user-images.githubusercontent.com/1024833/63966602-77f12e80-ca50-11e9-9efd-4a3370b04d1a.gif)

**Comment by phette23** [comment]
I tested everything in your list and only found contrast issues with the Twitter handle thing I posted above and still with some of the right sidebar text for Workshops:

![Screen Shot 2019-08-29 at 4 30 21 PM](https://user-images.githubusercontent.com/1024833/63983259-c61b2780-ca7a-11e9-82bd-e5c5ab389a8f.png)

What do you think about `.back-workshops { color: black }` and .talk-box-detail-value { color: black }` (or something close to black)? Then the font for the whole sidebar is dark on light background, I think it actually looks better that way.
