### ISSUE TITLE
Tracking document downloads

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#34]
use analytics

**Comment by dzoladz** [comment]
@phette23 There are a few ways to track downloads of the prospectus. 

**Without** the use of GA Tag Manager, I could add a tracking event to the `<a>` element in `prospectus/index.html` that gets clicked to view the PDF. I think the following attribute would be sufficient:

`onclick="ga('send', 'event', 'PDF', 'Download', 'Prospectus');"`

For reference, [Event Measurement Documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/events)

**With** the use of GA Tag Manager, it appears to be possible to more globally track engagement with binary objects by file extension, regex, or other factors. I'd need to have access to the account that own the GA property, or an admin would need to grant my OhioNET account access to the property with sufficient permissions to use Tag Manager.

As there hasn't been a demand for this information in the past, I'm inclined to simply implement the `onclick` attribute for tracking prospectus download events.

Thoughts?

**Comment by phette23** [comment]
`onclick` seems pretty easy and I'm not sure we'll have many more use cases so I'm OK with that. It's already kind of a mess adding everyone to the analytics property each year so I'm not inclined to add more of that with GTM.
