### ISSUE TITLE
create a coding style guide

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#35]
- [x] follow header hierarchies, careful when using includes
- [x] when to use _data file, when to write content into HTML templates
- [x] misc other guidelines? (indentation, ordering of CSS properties)
- [x] separate out Accessibility section

**Comment by phette23** [comment]
Started on this - https://github.com/code4lib/2020.code4lib.org/wiki/Coding-Guide

**Comment by kaitlinnewson** [comment]
Looks good to me - just added a small note about using empty alt tags if an image is decorative. Once we resolve #4 we should make sure to take another look.

**Comment by phette23** [comment]
- add note about BS classes to headings section
- link to a11y project checklist https://a11yproject.com/checklist/#section-headings
- note in readme contribution section about running accessibility audit before pushing structural changes
