### ISSUE TITLE
update Bootstrap?

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#4]
We're using Bootstrap v3.3.7 I believe (see comment at top of assets/_scss/boostrap/_bootstrap.scss) while 4.3 is available.

**Comment by Meng-MiamiOH** [comment]
Official migration doc: https://getbootstrap.com/docs/4.3/migration/

Third-party tool: http://upgrade-bootstrap.bootply.com/
This online tool shows 
1. The list of class changes 
2. Bootstrap 3.x HTML --> Bootstrap 4 HTML covert tool

**Comment by Meng-MiamiOH** [comment]
Created a google spreadsheet to indicate the amount of class names we need to replace, if upgrade from 3 to 4.
https://docs.google.com/spreadsheets/d/1bcKHk5WY8RbX6HLTardX1aOSBjoFTIk70eAtClsTtzE/edit?usp=sharing

**Comment by phette23** [comment]
# Speakers page / jQuery issue

The site loads its JavaScript in _includes/footer.html with this passage that checks to see if we already have jQuery before trying to load it:

```html
<script>window.jQuery || document.write('<script src="{{ "/assets/js/vendor/jquery-1.11.2.min.js" | relative_url }}"><\/script>')</script>
<script src="{{ "/assets/js/vendor/bootstrap.min.js" | relative_url }}"></script>

<script src="{{ "/assets/js/main.js" | relative_url }}"></script>
```

In the `updateBootstrap` branch you put the scripts in the `<head>` like so:

```html
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
```

So jQuery's slim version is used, causing the footer.html not to load a full version. Also, Bootstrap's JS [should go _after_ jQuery & Popper](https://getbootstrap.com/docs/4.0/getting-started/introduction/#js) because it depends on them. So what needs to happen is:

- delete the scripts in the <head>
- put them in the footer and overwrite the older versions
- use full version of jquery not slim

I can add a commit to `updateBootstrap` shortly that does this, just wanted to explain what was happening.

**Comment by phette23** [comment]
Also another note: your ruby gems "vendors" directory is still checked in on the updateBootstrap branch which can cause issues. I can't build the site properly with my ruby setup, for instance. I could push up a commit to delete it but I'm afraid it'd mess up @Meng-MiamiOH's ruby environment when pulled down. So Meng you should do something like this:

- edit .gitignore and add a line for "vendors/"
- run `git rm -rf --cached vendors` to remove that folder from git's tracking without deleting the local files

Let me know if that doesn't make sense, we can go over it in the meeting if we need to. We just need to do this before merging into master.
