### ISSUE TITLE
open preconference workshop voting on November 5th

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#50]

**Comment by dzoladz** [comment]
I've reopened this because I'm not seeing and end date or an active url to accept votes. Previously, a survey monkey account was used. I'm not sure if creating these forms is a task performed by the web team.

**Comment by phette23** [comment]
The Preconference Committee only just emailed me today:

> https://docs.google.com/forms/d/e/1FAIpQLSfEAwmP9Wnrk2aXLgfEpnk0zS3W8M4rukx_DL3tCeaMjqHwdg/viewform
> Voting was supposed to start today.  But I believe that the LPC wanted to start the voting once the keynote nominations and program session voting ends. Voting for pre-cons should end on November 19 at 11:59pm PT.

IMO we should just open the voting form tomorrow once keynote closes.

**Comment by dzoladz** [comment]
I'll need to add the workshop descriptions. But I don't believe I can download the response CSV to process.

**Comment by phette23** [comment]
We don't need to add descriptions for proposals, this was something I actually asked LPC about at their last meeting. Once workshops are finalized we'll add them but no need for proposals.

**Comment by dzoladz** [comment]
Sounds good. Rather than fiddle with the `_includes` at this point, I'll just incorporate some information text. If that doesn't work for you, we could always simply remove the `workshop-proposals.yml` file.
