### ISSUE TITLE
need keynote voting form and end date 

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2020.code4lib.org#58]
Following the `.yml` in the examples directory, I've added a `keynote-nominees.yml` file in `/_data`. It looks fine to me, but feel free to modify as necessary.

1. I can't find the link to collect votes for this year. Do we create that collection tool?

2. For the moment, I've set the end day to 11-26-2019. Has a closing date been released?

**Comment by kaitlinnewson** [comment]
We typically wait until we receive the voting form before opening it up on the website. This will be created by the keynote committee, and they'll send out a closing date as well.

**Comment by dzoladz** [comment]
Cool. I'm going to revert a few updates that I made this morning, as there's a similar scenario with the pre-conf voting form... and I updated the 'through' language on the site without updating my calendar reminder :) Apparently, I just do whatever my calendar says these days.

**Comment by phette23** [comment]
We have these now, see Clara Turp's email today.

Form - https://forms.gle/uDaMVX9nopjjNh5Y8
End date - 2019-12-02
