### ISSUE TITLE
Scholarship Sponsor Display

### ISSUE THREAD

**Issue by mjingle** [code4lib/2020.code4lib.org#67]
A sponsor currently displays on the diversity scholarship page with the annotation "Giveaway", which is potentially confusing. This sponsor donated both a diversity scholarship and a giveaway item. Generous, I know! :)

To solve: Would it be possible to have two entries in the data.yml - one for `diversity: true` and another with the giveaway annotation? Let me know your thoughts.

**Comment by phette23** [comment]
Not sure if this is easier but we might also consider simply hiding all annotations on the Diversity Scholarship page. I suspect that the sponsor is shown using an include but we could pass some kind of context variable to the include telling it that it's on the scholarships page.
