### ISSUE TITLE
populate speakers data and create posts for all talks

### ISSUE THREAD

**Issue by phette23** [code4lib/2020.code4lib.org#78]
With the announcement today of the accepted talks, we know that the Program Committee has a list of all accepted talks and their presenters. We'll need to populate _data/speaker.yml with the speaker data, obtain speaker images, and finally generate Jekyll posts using the CSV they provide us, as described in the wiki.

Adding `blocked` tag until we get the talks CSV data.

**Comment by phette23** [comment]
We got a spreadsheet of basic talk & speaker data, it's in the Drive folder.

**Comment by dzoladz** [comment]
I've created a PR for this issue using the data that I had available.
